/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-04-06 17:52:19 UTC)
 * on 2018-05-07 at 00:11:22 UTC 
 * Modify at your own risk.
 */

package com.appspot.hackwinds.hackwinds.model;

/**
 * Model definition for MessagesTideTideForecastMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the hackwinds. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesTideTideForecastMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private MessagesTideTideStationMessage station;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("tidal_event_forecast")
  private java.util.List<MessagesTideTideForecastDayMessage> tidalEventForecast;

  static {
    // hack to force ProGuard to consider MessagesTideTideForecastDayMessage used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(MessagesTideTideForecastDayMessage.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("water_level_forecast")
  private java.util.List<MessagesTideTideEventMessage> waterLevelForecast;

  /**
   * @return value or {@code null} for none
   */
  public MessagesTideTideStationMessage getStation() {
    return station;
  }

  /**
   * @param station station or {@code null} for none
   */
  public MessagesTideTideForecastMessage setStation(MessagesTideTideStationMessage station) {
    this.station = station;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MessagesTideTideForecastDayMessage> getTidalEventForecast() {
    return tidalEventForecast;
  }

  /**
   * @param tidalEventForecast tidalEventForecast or {@code null} for none
   */
  public MessagesTideTideForecastMessage setTidalEventForecast(java.util.List<MessagesTideTideForecastDayMessage> tidalEventForecast) {
    this.tidalEventForecast = tidalEventForecast;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MessagesTideTideEventMessage> getWaterLevelForecast() {
    return waterLevelForecast;
  }

  /**
   * @param waterLevelForecast waterLevelForecast or {@code null} for none
   */
  public MessagesTideTideForecastMessage setWaterLevelForecast(java.util.List<MessagesTideTideEventMessage> waterLevelForecast) {
    this.waterLevelForecast = waterLevelForecast;
    return this;
  }

  @Override
  public MessagesTideTideForecastMessage set(String fieldName, Object value) {
    return (MessagesTideTideForecastMessage) super.set(fieldName, value);
  }

  @Override
  public MessagesTideTideForecastMessage clone() {
    return (MessagesTideTideForecastMessage) super.clone();
  }

}
