/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-04-06 17:52:19 UTC)
 * on 2018-05-07 at 00:11:22 UTC 
 * Modify at your own risk.
 */

package com.appspot.hackwinds.hackwinds.model;

/**
 * Model definition for MessagesSunSunMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the hackwinds. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesSunSunMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime sunrise;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime sunset;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getSunrise() {
    return sunrise;
  }

  /**
   * @param sunrise sunrise or {@code null} for none
   */
  public MessagesSunSunMessage setSunrise(com.google.api.client.util.DateTime sunrise) {
    this.sunrise = sunrise;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getSunset() {
    return sunset;
  }

  /**
   * @param sunset sunset or {@code null} for none
   */
  public MessagesSunSunMessage setSunset(com.google.api.client.util.DateTime sunset) {
    this.sunset = sunset;
    return this;
  }

  @Override
  public MessagesSunSunMessage set(String fieldName, Object value) {
    return (MessagesSunSunMessage) super.set(fieldName, value);
  }

  @Override
  public MessagesSunSunMessage clone() {
    return (MessagesSunSunMessage) super.clone();
  }

}
