/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-04-06 17:52:19 UTC)
 * on 2018-05-07 at 00:11:22 UTC 
 * Modify at your own risk.
 */

package com.appspot.hackwinds.hackwinds.model;

/**
 * Model definition for MessagesTideTideStationMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the hackwinds. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesTideTideStationMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private MessagesLocationLocationMessage location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String state;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("station_id")
  private java.lang.String stationId;

  /**
   * @return value or {@code null} for none
   */
  public MessagesLocationLocationMessage getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public MessagesTideTideStationMessage setLocation(MessagesLocationLocationMessage location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getState() {
    return state;
  }

  /**
   * @param state state or {@code null} for none
   */
  public MessagesTideTideStationMessage setState(java.lang.String state) {
    this.state = state;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationId() {
    return stationId;
  }

  /**
   * @param stationId stationId or {@code null} for none
   */
  public MessagesTideTideStationMessage setStationId(java.lang.String stationId) {
    this.stationId = stationId;
    return this;
  }

  @Override
  public MessagesTideTideStationMessage set(String fieldName, Object value) {
    return (MessagesTideTideStationMessage) super.set(fieldName, value);
  }

  @Override
  public MessagesTideTideStationMessage clone() {
    return (MessagesTideTideStationMessage) super.clone();
  }

}
