/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-04-06 17:52:19 UTC)
 * on 2018-05-07 at 00:11:22 UTC 
 * Modify at your own risk.
 */

package com.appspot.hackwinds.hackwinds.model;

/**
 * Model definition for MessagesDataSurfForecastMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the hackwinds. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesDataSurfForecastMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fetch_date")
  private com.google.api.client.util.DateTime fetchDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<MessagesDataSurfForecastDayMessage> forecast;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("forecast_location")
  private MessagesLocationLocationMessage forecastLocation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("swell_location")
  private MessagesLocationLocationMessage swellLocation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("wave_model_info")
  private MessagesNoaamodelNOAAModelMessage waveModelInfo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("weather_model_info")
  private MessagesNoaamodelNOAAModelMessage weatherModelInfo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("wind_location")
  private MessagesLocationLocationMessage windLocation;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFetchDate() {
    return fetchDate;
  }

  /**
   * @param fetchDate fetchDate or {@code null} for none
   */
  public MessagesDataSurfForecastMessage setFetchDate(com.google.api.client.util.DateTime fetchDate) {
    this.fetchDate = fetchDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<MessagesDataSurfForecastDayMessage> getForecast() {
    return forecast;
  }

  /**
   * @param forecast forecast or {@code null} for none
   */
  public MessagesDataSurfForecastMessage setForecast(java.util.List<MessagesDataSurfForecastDayMessage> forecast) {
    this.forecast = forecast;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public MessagesLocationLocationMessage getForecastLocation() {
    return forecastLocation;
  }

  /**
   * @param forecastLocation forecastLocation or {@code null} for none
   */
  public MessagesDataSurfForecastMessage setForecastLocation(MessagesLocationLocationMessage forecastLocation) {
    this.forecastLocation = forecastLocation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public MessagesLocationLocationMessage getSwellLocation() {
    return swellLocation;
  }

  /**
   * @param swellLocation swellLocation or {@code null} for none
   */
  public MessagesDataSurfForecastMessage setSwellLocation(MessagesLocationLocationMessage swellLocation) {
    this.swellLocation = swellLocation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public MessagesNoaamodelNOAAModelMessage getWaveModelInfo() {
    return waveModelInfo;
  }

  /**
   * @param waveModelInfo waveModelInfo or {@code null} for none
   */
  public MessagesDataSurfForecastMessage setWaveModelInfo(MessagesNoaamodelNOAAModelMessage waveModelInfo) {
    this.waveModelInfo = waveModelInfo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public MessagesNoaamodelNOAAModelMessage getWeatherModelInfo() {
    return weatherModelInfo;
  }

  /**
   * @param weatherModelInfo weatherModelInfo or {@code null} for none
   */
  public MessagesDataSurfForecastMessage setWeatherModelInfo(MessagesNoaamodelNOAAModelMessage weatherModelInfo) {
    this.weatherModelInfo = weatherModelInfo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public MessagesLocationLocationMessage getWindLocation() {
    return windLocation;
  }

  /**
   * @param windLocation windLocation or {@code null} for none
   */
  public MessagesDataSurfForecastMessage setWindLocation(MessagesLocationLocationMessage windLocation) {
    this.windLocation = windLocation;
    return this;
  }

  @Override
  public MessagesDataSurfForecastMessage set(String fieldName, Object value) {
    return (MessagesDataSurfForecastMessage) super.set(fieldName, value);
  }

  @Override
  public MessagesDataSurfForecastMessage clone() {
    return (MessagesDataSurfForecastMessage) super.clone();
  }

}
