/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-02-26 17:53:51 UTC)
 * on 2018-04-12 at 20:28:40 UTC 
 * Modify at your own risk.
 */

package com.appspot.hackwinds.hackwinds.model;

/**
 * Model definition for ModelCameraMessagesCameraRegionMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the hackwinds. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ModelCameraMessagesCameraRegionMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ModelCameraMessagesCameraMessage> cameras;

  static {
    // hack to force ProGuard to consider ModelCameraMessagesCameraMessage used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(ModelCameraMessagesCameraMessage.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ModelCameraMessagesCameraMessage> getCameras() {
    return cameras;
  }

  /**
   * @param cameras cameras or {@code null} for none
   */
  public ModelCameraMessagesCameraRegionMessage setCameras(java.util.List<ModelCameraMessagesCameraMessage> cameras) {
    this.cameras = cameras;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public ModelCameraMessagesCameraRegionMessage setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  @Override
  public ModelCameraMessagesCameraRegionMessage set(String fieldName, Object value) {
    return (ModelCameraMessagesCameraRegionMessage) super.set(fieldName, value);
  }

  @Override
  public ModelCameraMessagesCameraRegionMessage clone() {
    return (ModelCameraMessagesCameraRegionMessage) super.clone();
  }

}
