/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-02-26 17:53:51 UTC)
 * on 2018-04-12 at 20:28:40 UTC 
 * Modify at your own risk.
 */

package com.appspot.hackwinds.hackwinds.model;

/**
 * Model definition for ModelForecastMessagesSurfForecastDayMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the hackwinds. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ModelForecastMessagesSurfForecastDayMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ModelForecastMessagesDataMessage> data;

  static {
    // hack to force ProGuard to consider ModelForecastMessagesDataMessage used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(ModelForecastMessagesDataMessage.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ModelForecastMessagesSurfForecastSummaryMessage> summary;

  static {
    // hack to force ProGuard to consider ModelForecastMessagesSurfForecastSummaryMessage used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(ModelForecastMessagesSurfForecastSummaryMessage.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ModelForecastMessagesDataMessage> getData() {
    return data;
  }

  /**
   * @param data data or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastDayMessage setData(java.util.List<ModelForecastMessagesDataMessage> data) {
    this.data = data;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastDayMessage setDate(com.google.api.client.util.DateTime date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ModelForecastMessagesSurfForecastSummaryMessage> getSummary() {
    return summary;
  }

  /**
   * @param summary summary or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastDayMessage setSummary(java.util.List<ModelForecastMessagesSurfForecastSummaryMessage> summary) {
    this.summary = summary;
    return this;
  }

  @Override
  public ModelForecastMessagesSurfForecastDayMessage set(String fieldName, Object value) {
    return (ModelForecastMessagesSurfForecastDayMessage) super.set(fieldName, value);
  }

  @Override
  public ModelForecastMessagesSurfForecastDayMessage clone() {
    return (ModelForecastMessagesSurfForecastDayMessage) super.clone();
  }

}
