/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-02-26 17:53:51 UTC)
 * on 2018-04-12 at 20:28:40 UTC 
 * Modify at your own risk.
 */

package com.appspot.hackwinds.hackwinds.model;

/**
 * Model definition for ModelCameraMessagesCameraLocationsMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the hackwinds. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ModelCameraMessagesCameraLocationsMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("camera_locations")
  private java.util.List<ModelCameraMessagesCameraRegionMessage> cameraLocations;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ModelCameraMessagesCameraRegionMessage> getCameraLocations() {
    return cameraLocations;
  }

  /**
   * @param cameraLocations cameraLocations or {@code null} for none
   */
  public ModelCameraMessagesCameraLocationsMessage setCameraLocations(java.util.List<ModelCameraMessagesCameraRegionMessage> cameraLocations) {
    this.cameraLocations = cameraLocations;
    return this;
  }

  @Override
  public ModelCameraMessagesCameraLocationsMessage set(String fieldName, Object value) {
    return (ModelCameraMessagesCameraLocationsMessage) super.set(fieldName, value);
  }

  @Override
  public ModelCameraMessagesCameraLocationsMessage clone() {
    return (ModelCameraMessagesCameraLocationsMessage) super.clone();
  }

}
