/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-02-26 17:53:51 UTC)
 * on 2018-04-12 at 20:28:40 UTC 
 * Modify at your own risk.
 */

package com.appspot.hackwinds.hackwinds.model;

/**
 * Model definition for ModelForecastMessagesSurfForecastMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the hackwinds. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ModelForecastMessagesSurfForecastMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fetch_date")
  private com.google.api.client.util.DateTime fetchDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ModelForecastMessagesSurfForecastDayMessage> forecast;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("forecast_location")
  private ModelForecastMessagesLocationMessage forecastLocation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("swell_location")
  private ModelForecastMessagesLocationMessage swellLocation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("wave_model_info")
  private ModelForecastMessagesNOAAModelMessage waveModelInfo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("weather_model_info")
  private ModelForecastMessagesNOAAModelMessage weatherModelInfo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("wind_location")
  private ModelForecastMessagesLocationMessage windLocation;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFetchDate() {
    return fetchDate;
  }

  /**
   * @param fetchDate fetchDate or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastMessage setFetchDate(com.google.api.client.util.DateTime fetchDate) {
    this.fetchDate = fetchDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ModelForecastMessagesSurfForecastDayMessage> getForecast() {
    return forecast;
  }

  /**
   * @param forecast forecast or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastMessage setForecast(java.util.List<ModelForecastMessagesSurfForecastDayMessage> forecast) {
    this.forecast = forecast;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ModelForecastMessagesLocationMessage getForecastLocation() {
    return forecastLocation;
  }

  /**
   * @param forecastLocation forecastLocation or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastMessage setForecastLocation(ModelForecastMessagesLocationMessage forecastLocation) {
    this.forecastLocation = forecastLocation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ModelForecastMessagesLocationMessage getSwellLocation() {
    return swellLocation;
  }

  /**
   * @param swellLocation swellLocation or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastMessage setSwellLocation(ModelForecastMessagesLocationMessage swellLocation) {
    this.swellLocation = swellLocation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ModelForecastMessagesNOAAModelMessage getWaveModelInfo() {
    return waveModelInfo;
  }

  /**
   * @param waveModelInfo waveModelInfo or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastMessage setWaveModelInfo(ModelForecastMessagesNOAAModelMessage waveModelInfo) {
    this.waveModelInfo = waveModelInfo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ModelForecastMessagesNOAAModelMessage getWeatherModelInfo() {
    return weatherModelInfo;
  }

  /**
   * @param weatherModelInfo weatherModelInfo or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastMessage setWeatherModelInfo(ModelForecastMessagesNOAAModelMessage weatherModelInfo) {
    this.weatherModelInfo = weatherModelInfo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ModelForecastMessagesLocationMessage getWindLocation() {
    return windLocation;
  }

  /**
   * @param windLocation windLocation or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastMessage setWindLocation(ModelForecastMessagesLocationMessage windLocation) {
    this.windLocation = windLocation;
    return this;
  }

  @Override
  public ModelForecastMessagesSurfForecastMessage set(String fieldName, Object value) {
    return (ModelForecastMessagesSurfForecastMessage) super.set(fieldName, value);
  }

  @Override
  public ModelForecastMessagesSurfForecastMessage clone() {
    return (ModelForecastMessagesSurfForecastMessage) super.clone();
  }

}
