/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-02-26 17:53:51 UTC)
 * on 2018-04-12 at 20:28:40 UTC 
 * Modify at your own risk.
 */

package com.appspot.hackwinds.hackwinds.model;

/**
 * Model definition for ModelForecastMessagesSurfForecastSummaryMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the hackwinds. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ModelForecastMessagesSurfForecastSummaryMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String conditions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String summary;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("time_of_day")
  private java.lang.String timeOfDay;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getConditions() {
    return conditions;
  }

  /**
   * @param conditions conditions or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastSummaryMessage setConditions(java.lang.String conditions) {
    this.conditions = conditions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSummary() {
    return summary;
  }

  /**
   * @param summary summary or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastSummaryMessage setSummary(java.lang.String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTimeOfDay() {
    return timeOfDay;
  }

  /**
   * @param timeOfDay timeOfDay or {@code null} for none
   */
  public ModelForecastMessagesSurfForecastSummaryMessage setTimeOfDay(java.lang.String timeOfDay) {
    this.timeOfDay = timeOfDay;
    return this;
  }

  @Override
  public ModelForecastMessagesSurfForecastSummaryMessage set(String fieldName, Object value) {
    return (ModelForecastMessagesSurfForecastSummaryMessage) super.set(fieldName, value);
  }

  @Override
  public ModelForecastMessagesSurfForecastSummaryMessage clone() {
    return (ModelForecastMessagesSurfForecastSummaryMessage) super.clone();
  }

}
