/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-11-07 19:12:12 UTC)
 * on 2017-11-12 at 01:28:45 UTC 
 * Modify at your own risk.
 */

package com.appspot.mpitester_13.station.model;

/**
 * Model definition for ApiApiMessagesStationsMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the station. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApiApiMessagesStationsMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fetch_date")
  private com.google.api.client.util.DateTime fetchDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ApiApiMessagesStationMessage> stations;

  static {
    // hack to force ProGuard to consider ApiApiMessagesStationMessage used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(ApiApiMessagesStationMessage.class);
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFetchDate() {
    return fetchDate;
  }

  /**
   * @param fetchDate fetchDate or {@code null} for none
   */
  public ApiApiMessagesStationsMessage setFetchDate(com.google.api.client.util.DateTime fetchDate) {
    this.fetchDate = fetchDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ApiApiMessagesStationMessage> getStations() {
    return stations;
  }

  /**
   * @param stations stations or {@code null} for none
   */
  public ApiApiMessagesStationsMessage setStations(java.util.List<ApiApiMessagesStationMessage> stations) {
    this.stations = stations;
    return this;
  }

  @Override
  public ApiApiMessagesStationsMessage set(String fieldName, Object value) {
    return (ApiApiMessagesStationsMessage) super.set(fieldName, value);
  }

  @Override
  public ApiApiMessagesStationsMessage clone() {
    return (ApiApiMessagesStationsMessage) super.clone();
  }

}
