/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-11-07 19:12:12 UTC)
 * on 2017-11-12 at 01:28:45 UTC 
 * Modify at your own risk.
 */

package com.appspot.mpitester_13.station.model;

/**
 * Model definition for ApiApiMessagesStationMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the station. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApiApiMessagesStationMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean active;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean currents;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean dart;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ApiApiMessagesDataMessage> data;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ApiApiMessagesLocationMessage location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String owner;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String program;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("station_id")
  private java.lang.String stationId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("station_type")
  private java.lang.String stationType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("water_quality")
  private java.lang.Boolean waterQuality;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getActive() {
    return active;
  }

  /**
   * @param active active or {@code null} for none
   */
  public ApiApiMessagesStationMessage setActive(java.lang.Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCurrents() {
    return currents;
  }

  /**
   * @param currents currents or {@code null} for none
   */
  public ApiApiMessagesStationMessage setCurrents(java.lang.Boolean currents) {
    this.currents = currents;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDart() {
    return dart;
  }

  /**
   * @param dart dart or {@code null} for none
   */
  public ApiApiMessagesStationMessage setDart(java.lang.Boolean dart) {
    this.dart = dart;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ApiApiMessagesDataMessage> getData() {
    return data;
  }

  /**
   * @param data data or {@code null} for none
   */
  public ApiApiMessagesStationMessage setData(java.util.List<ApiApiMessagesDataMessage> data) {
    this.data = data;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ApiApiMessagesLocationMessage getLocation() {
    return location;
  }

  /**
   * @param location location or {@code null} for none
   */
  public ApiApiMessagesStationMessage setLocation(ApiApiMessagesLocationMessage location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public ApiApiMessagesStationMessage setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOwner() {
    return owner;
  }

  /**
   * @param owner owner or {@code null} for none
   */
  public ApiApiMessagesStationMessage setOwner(java.lang.String owner) {
    this.owner = owner;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProgram() {
    return program;
  }

  /**
   * @param program program or {@code null} for none
   */
  public ApiApiMessagesStationMessage setProgram(java.lang.String program) {
    this.program = program;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationId() {
    return stationId;
  }

  /**
   * @param stationId stationId or {@code null} for none
   */
  public ApiApiMessagesStationMessage setStationId(java.lang.String stationId) {
    this.stationId = stationId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationType() {
    return stationType;
  }

  /**
   * @param stationType stationType or {@code null} for none
   */
  public ApiApiMessagesStationMessage setStationType(java.lang.String stationType) {
    this.stationType = stationType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getWaterQuality() {
    return waterQuality;
  }

  /**
   * @param waterQuality waterQuality or {@code null} for none
   */
  public ApiApiMessagesStationMessage setWaterQuality(java.lang.Boolean waterQuality) {
    this.waterQuality = waterQuality;
    return this;
  }

  @Override
  public ApiApiMessagesStationMessage set(String fieldName, Object value) {
    return (ApiApiMessagesStationMessage) super.set(fieldName, value);
  }

  @Override
  public ApiApiMessagesStationMessage clone() {
    return (ApiApiMessagesStationMessage) super.clone();
  }

}
