/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-11-07 19:12:12 UTC)
 * on 2017-11-12 at 01:28:45 UTC 
 * Modify at your own risk.
 */

package com.appspot.mpitester_13.station.model;

/**
 * Model definition for ApiApiMessagesDataMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the station. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApiApiMessagesDataMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("air_temperature")
  private java.lang.Double airTemperature;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("average_period")
  private java.lang.Double averagePeriod;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("dewpoint_temperature")
  private java.lang.Double dewpointTemperature;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("direction_spectra_plot")
  private java.lang.String directionSpectraPlot;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("energy_spectra_plot")
  private java.lang.String energySpectraPlot;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double pressure;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("pressure_tendency")
  private java.lang.Double pressureTendency;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String steepness;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("swell_components")
  private java.util.List<ApiApiMessagesSwellMessage> swellComponents;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ApiApiMessagesUnitLabelMessage units;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("water_level")
  private java.lang.Double waterLevel;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("water_temperature")
  private java.lang.Double waterTemperature;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("wave_spectra")
  private ApiApiMessagesWaveSpectraMessage waveSpectra;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("wave_summary")
  private ApiApiMessagesSwellMessage waveSummary;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("wind_compass_direction")
  private java.lang.String windCompassDirection;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("wind_direction")
  private java.lang.Double windDirection;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("wind_gust")
  private java.lang.Double windGust;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("wind_speed")
  private java.lang.Double windSpeed;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getAirTemperature() {
    return airTemperature;
  }

  /**
   * @param airTemperature airTemperature or {@code null} for none
   */
  public ApiApiMessagesDataMessage setAirTemperature(java.lang.Double airTemperature) {
    this.airTemperature = airTemperature;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getAveragePeriod() {
    return averagePeriod;
  }

  /**
   * @param averagePeriod averagePeriod or {@code null} for none
   */
  public ApiApiMessagesDataMessage setAveragePeriod(java.lang.Double averagePeriod) {
    this.averagePeriod = averagePeriod;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public ApiApiMessagesDataMessage setDate(com.google.api.client.util.DateTime date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getDewpointTemperature() {
    return dewpointTemperature;
  }

  /**
   * @param dewpointTemperature dewpointTemperature or {@code null} for none
   */
  public ApiApiMessagesDataMessage setDewpointTemperature(java.lang.Double dewpointTemperature) {
    this.dewpointTemperature = dewpointTemperature;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDirectionSpectraPlot() {
    return directionSpectraPlot;
  }

  /**
   * @param directionSpectraPlot directionSpectraPlot or {@code null} for none
   */
  public ApiApiMessagesDataMessage setDirectionSpectraPlot(java.lang.String directionSpectraPlot) {
    this.directionSpectraPlot = directionSpectraPlot;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEnergySpectraPlot() {
    return energySpectraPlot;
  }

  /**
   * @param energySpectraPlot energySpectraPlot or {@code null} for none
   */
  public ApiApiMessagesDataMessage setEnergySpectraPlot(java.lang.String energySpectraPlot) {
    this.energySpectraPlot = energySpectraPlot;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getPressure() {
    return pressure;
  }

  /**
   * @param pressure pressure or {@code null} for none
   */
  public ApiApiMessagesDataMessage setPressure(java.lang.Double pressure) {
    this.pressure = pressure;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getPressureTendency() {
    return pressureTendency;
  }

  /**
   * @param pressureTendency pressureTendency or {@code null} for none
   */
  public ApiApiMessagesDataMessage setPressureTendency(java.lang.Double pressureTendency) {
    this.pressureTendency = pressureTendency;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSteepness() {
    return steepness;
  }

  /**
   * @param steepness steepness or {@code null} for none
   */
  public ApiApiMessagesDataMessage setSteepness(java.lang.String steepness) {
    this.steepness = steepness;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ApiApiMessagesSwellMessage> getSwellComponents() {
    return swellComponents;
  }

  /**
   * @param swellComponents swellComponents or {@code null} for none
   */
  public ApiApiMessagesDataMessage setSwellComponents(java.util.List<ApiApiMessagesSwellMessage> swellComponents) {
    this.swellComponents = swellComponents;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ApiApiMessagesUnitLabelMessage getUnits() {
    return units;
  }

  /**
   * @param units units or {@code null} for none
   */
  public ApiApiMessagesDataMessage setUnits(ApiApiMessagesUnitLabelMessage units) {
    this.units = units;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getWaterLevel() {
    return waterLevel;
  }

  /**
   * @param waterLevel waterLevel or {@code null} for none
   */
  public ApiApiMessagesDataMessage setWaterLevel(java.lang.Double waterLevel) {
    this.waterLevel = waterLevel;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getWaterTemperature() {
    return waterTemperature;
  }

  /**
   * @param waterTemperature waterTemperature or {@code null} for none
   */
  public ApiApiMessagesDataMessage setWaterTemperature(java.lang.Double waterTemperature) {
    this.waterTemperature = waterTemperature;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ApiApiMessagesWaveSpectraMessage getWaveSpectra() {
    return waveSpectra;
  }

  /**
   * @param waveSpectra waveSpectra or {@code null} for none
   */
  public ApiApiMessagesDataMessage setWaveSpectra(ApiApiMessagesWaveSpectraMessage waveSpectra) {
    this.waveSpectra = waveSpectra;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ApiApiMessagesSwellMessage getWaveSummary() {
    return waveSummary;
  }

  /**
   * @param waveSummary waveSummary or {@code null} for none
   */
  public ApiApiMessagesDataMessage setWaveSummary(ApiApiMessagesSwellMessage waveSummary) {
    this.waveSummary = waveSummary;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWindCompassDirection() {
    return windCompassDirection;
  }

  /**
   * @param windCompassDirection windCompassDirection or {@code null} for none
   */
  public ApiApiMessagesDataMessage setWindCompassDirection(java.lang.String windCompassDirection) {
    this.windCompassDirection = windCompassDirection;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getWindDirection() {
    return windDirection;
  }

  /**
   * @param windDirection windDirection or {@code null} for none
   */
  public ApiApiMessagesDataMessage setWindDirection(java.lang.Double windDirection) {
    this.windDirection = windDirection;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getWindGust() {
    return windGust;
  }

  /**
   * @param windGust windGust or {@code null} for none
   */
  public ApiApiMessagesDataMessage setWindGust(java.lang.Double windGust) {
    this.windGust = windGust;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getWindSpeed() {
    return windSpeed;
  }

  /**
   * @param windSpeed windSpeed or {@code null} for none
   */
  public ApiApiMessagesDataMessage setWindSpeed(java.lang.Double windSpeed) {
    this.windSpeed = windSpeed;
    return this;
  }

  @Override
  public ApiApiMessagesDataMessage set(String fieldName, Object value) {
    return (ApiApiMessagesDataMessage) super.set(fieldName, value);
  }

  @Override
  public ApiApiMessagesDataMessage clone() {
    return (ApiApiMessagesDataMessage) super.clone();
  }

}
