/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-11-07 19:12:12 UTC)
 * on 2017-11-12 at 01:28:45 UTC 
 * Modify at your own risk.
 */

package com.appspot.mpitester_13.station.model;

/**
 * Model definition for ApiApiMessagesPlotMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the station. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ApiApiMessagesPlotMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String plot;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("station_id")
  private java.lang.String stationId;

  /**
   * @see #decodePlot()
   * @return value or {@code null} for none
   */
  public java.lang.String getPlot() {
    return plot;
  }

  /**

   * @see #getPlot()
   * @return Base64 decoded value or {@code null} for none
   *
   * @since 1.14
   */
  public byte[] decodePlot() {
    return com.google.api.client.util.Base64.decodeBase64(plot);
  }

  /**
   * @see #encodePlot()
   * @param plot plot or {@code null} for none
   */
  public ApiApiMessagesPlotMessage setPlot(java.lang.String plot) {
    this.plot = plot;
    return this;
  }

  /**

   * @see #setPlot()
   *
   * <p>
   * The value is encoded Base64 or {@code null} for none.
   * </p>
   *
   * @since 1.14
   */
  public ApiApiMessagesPlotMessage encodePlot(byte[] plot) {
    this.plot = com.google.api.client.util.Base64.encodeBase64URLSafeString(plot);
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStationId() {
    return stationId;
  }

  /**
   * @param stationId stationId or {@code null} for none
   */
  public ApiApiMessagesPlotMessage setStationId(java.lang.String stationId) {
    this.stationId = stationId;
    return this;
  }

  @Override
  public ApiApiMessagesPlotMessage set(String fieldName, Object value) {
    return (ApiApiMessagesPlotMessage) super.set(fieldName, value);
  }

  @Override
  public ApiApiMessagesPlotMessage clone() {
    return (ApiApiMessagesPlotMessage) super.clone();
  }

}
